compatible with php 8.2, php Fatal error in server_status.php...
server_status.php - moniter tab, errors display
Fatal error: Uncaught Exception: Serialization of 'variant' is not allowed in [no active file]:0 Stack trace: #0 {main} thrown in [no active file] on line 0

traced error caused by server_status.php ,  line 156

$sysinfo = PMA_getSysInfo();
$memory  = $sysinfo->memory();

infact  libraries/sysinfo.lib.php